# -*- coding: utf-8 -*-
"""dataStory.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y1Gd_a66btEcjCJ_BY0lga1FtZXUZH0S

Data Story Code
"""

from google.colab import files
csvData = files.upload()

import statistics
import pandas as panda
import plotly.express as px
import csv
import plotly.figure_factory as ff
import random
import numpy as np
df = panda.read_csv("saveData.csv")

scGraph = px.bar(df,x="female",y="quant_saved")
scGraph.show()

data = df["quant_saved"].tolist()
mean = statistics.mean(data)
print("Mean of money saved: "+ str(mean))

median = statistics.median(data)
print("Median of money saved: "+ str(median))

mode = statistics.mode(data)
print("Mode of money saved: "+ str(mode))

std = statistics.stdev(data)
print("Standard Deviation of money saved: "+ str(std))

sex = df["female"].tolist()

mean2 = statistics.mean(sex)
print("Mean of females: "+ str(mean2))

median2 = statistics.median(sex)
print("Median of females: "+ str(median2))

mode2 = statistics.mode(sex)
print("Mode of females: "+ str(mode2))

std2 = statistics.stdev(sex)
print("Standard Deviation of females to males: "+ str(std2))

with open("saveData.csv", newline='') as f:
  read = csv.reader(f)
  newData = list(read)
  
newData.pop(0)
people = len(newData)
female = 0
for data in newData:
  if int(data[1]) == 1:
    female += 1
print("Females: " + str(female))
print("Males: " + str(people-female))